databases:
  - name: ELTraning
    databaseName: el_training_production
    user: el_training
    region: singapore

services:
  - type: web
    name: ELTraning
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ELTraning
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
