databases:
  - name: ELTraning
    databaseName: el_training_production
    user: el_training
    region: singapore

services:
  - type: web
    name: ELTraning
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: ELTraning
          property: host
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: APP_HOST
        fromService:
          type: web
          name: ELTraning
          property: connectionString
