version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - setup

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:3.1.2
      - image: circleci/postgres:14.0
        name: "db"
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: RuboCop
          command: bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - test:
          requires:
            - build